name:  ci

on:
  push:
    branches: [ shah ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        uses: shahpoorjan/composit-actions-repo/tree/main/docker-build@main
        with:
          image-name: fastapi-app