name: Deploy to Droplet

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with: 
          host: 159.203.179.160
          username: root
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /root/project-app-fastapi
            git pull origin main
            sudo systemctl restart fastapi